# Generated by Django 5.1 on 2024-09-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
