# Generated by Django 5.1 on 2024-09-01 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_todo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='last_uplate',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 18, 4, 5, 117262)),
        ),
    ]
